[package]
name = "rr-engine"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
barter-data = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
rr-storage = { path = "../rr-storage" }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
